ControlKit.Constant =
{
    PADDING_WRAPPER : 12,
    PADDING_OPTIONS : 2,
    MIN_HEIGHT      : 25,
    MIN_WIDTH       : 100,

    PADDING_PRESET  : 20,

    SCROLLBAR_BTN_HEIGHT    : 17,
    SCROLLBAR_TRACK_PADDING : 2
};