ControlKit.Constant =
{
    PADDING_WRAPPER : 12,
    PADDING_OPTIONS : 2,
    MIN_HEIGHT      : 25,
    MIN_WIDTH       : 100,

    PADDING_PRESET  : 20,

    SCROLLBAR_BTN_HEIGHT    : 17,
    SCROLLBAR_TRACK_PADDING : 2,

    HISTORY_MAX_STATES : 30,

    NUMBER_INPUT_SHIFT_MULTIPLIER : 10,

    CANVAS_ANTIALIAS   : false,
    CANVAS_FONT_FAMILY : 'Arial',
    CANVAS_FONT_SIZE   : 10
};